version: '3.5'
 
services:
  appfacilita:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: appfacilita
    restart: always
    ports:
      - 8080:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
